### ISSUE TITLE
monitor: add monitor service in docker-compose

### ISSUE THREAD

**Issue by skyzh** [sjtug/mirror-docker-siyuan#45]
We plan to add the following monitoring service on siyuan mirror.

* cAdvisor for monitoring network flow of each container.
* node-exporter for monitoring host status.

Reference: https://github.com/stefanprodan/dockprom/blob/master/docker-compose.yml for node_exporter

Reference: https://prometheus.io/docs/guides/cadvisor/#docker-compose-configuration

```
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
```

After that, we reverse-proxy these metrics in caddy with ip address limit. Ziqi and me will work on this config later.
